### ISSUE TITLE
java.lang.NoClassDefFoundError Could not initialize class: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl

### ISSUE THREAD

**Issue by alexkvak** [Itiviti/simple-slack-api#230]
I use this library in my teamcity plugin. So when I updated dependency from 1.0.0 to 1.2.0 I become runtime error
`Could not initialize class: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl`

Could you help me to fix this issue?

**Comment by alexkvak** [comment]
Found the solution: #274
