### PR TITLE
fix: LoggerFactory has different implementation in runtime.

### LINKED ISSUE #230: java.lang.NoClassDefFoundError Could not initialize class: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl
I use this library in my teamcity plugin. So when I updated dependency from 1.0.0 to 1.2.0 I become runtime error
`Could not initialize class: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl`

Could you help me to fix this issue?

### PR DESCRIPTION
**Pull request by alexkvak**
Complete Error: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of jetbrains/buildServer/plugins/classLoaders/PluginStandaloneClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/catalina/loader/ParallelWebappClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

Closes #230

### CODE REVIEW

**Comment by alexkvak** [comment]
@gluck do you still support this repo? Is there any chance to merge this PR and release new version?
